    name: 🐞 Bug report
    description: Report a reproducible issue
    labels: [bug]
    body:
      - type: textarea
        id: description
        attributes:
          label: What happened?
          description: A clear and concise description of the bug.
          placeholder: Tell us what you saw...
        validations:
          required: true
      - type: textarea
        id: steps
        attributes:
          label: Steps to reproduce
          description: Provide steps to reproduce.
          placeholder: 1. Go to '...'
2. Click on '...'
3. See error
        validations:
          required: true
      - type: input
        id: version
        attributes:
          label: Version / commit
          placeholder: v1.2.3 or commit SHA
      - type: textarea
        id: logs
        attributes:
          label: Relevant logs/stack traces
          render: shell
