name: ✨ Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      placeholder: I'm frustrated when...
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      placeholder: It would be great if...
      validations:
        required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives you've considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context
